# name: npm Audit Security Check

# on: [push]

# jobs:
#   audit:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v6

#       - name: Set up Node.js
#         uses: actions/setup-node@v6
#         with:
#           node-version: '24'

#       - name: Install dependencies
#         run: npm ci

#       - name: Run npm audit
#         run: npm audit --audit-level=high